### ISSUE TITLE
hello,when execute  npm run dev  get  error  ;please help

### ISSUE THREAD

**Issue by duanshuyong0** [Jannchie/anichart.js#1]
git clone and then  npm  install   and npm run  dev

<img width="727" alt="1601283464(1)" src="https://user-images.githubusercontent.com/1674662/94412292-34657880-01ac-11eb-85cb-87c02c33870a.png">

**Comment by Jannchie** [comment]
Well, that's because I didn't upload the test data to Github.
Now that I have uploaded the test data, you can browse the sample using the following command:
```
npm run serve
```
It's important to note that this project is just beginning to be maintained and isn't very easy to use -- to put it more bluntly, right now, it's hard to make a finished video unless you read the source code.
